config/routes.rb
Rails.application.routes.draw do
  get '' => 'hospitals#busca_hospitais'
  get '/map' => 'hospitals#showmap'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hospital.rb
class Hospital < ApplicationRecord
    geocoded_by :address, :latitude  => :nu_latitude, :longitude => :nu_longitude
    after_validation :geocode
    
    def address
        [no_logradouro, nu_endereco, no_complemento, no_bairro].compact.join(', ')
    end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/hospitals_controller.rb
class HospitalsController < ApplicationController
  before_action :set_hospital, only: [:show, :edit, :update, :destroy]

  # GET /hospitals
  # GET /hospitals.json
  def index
    @hospitals = Hospital.where("co_municipio_gestor = '261160'")
  end

  def busca_hospitais
    @hospitals = Hospital.where("co_municipio_gestor = '261160'")
  end

  def showmap
    @centrossaude = Hospital.where(["co_municipio_gestor = ? and tp_unidade = ?", "261160", "2"])
    @consultorios = Hospital.where(["co_municipio_gestor = ? and tp_unidade = ?", "261160", "22"])
    @clinicas = Hospital.where(["co_municipio_gestor = ? and tp_unidade = ?", "261160", "36"])
    @hospgerais = Hospital.where(["co_municipio_gestor = ? and tp_unidade = ?", "261160", "5"])
    @hospespecializados = Hospital.where(["co_municipio_gestor = ? and tp_unidade = ?", "261160", "7"])
  end

  # GET /hospitals/1
  # GET /hospitals/1.json
  def show
  end

  # GET /hospitals/new
  def new
    @hospital = Hospital.new
  end

  # GET /hospitals/1/edit
  def edit
  end

  # POST /hospitals
  # POST /hospitals.json
  def create
    @hospital = Hospital.new(hospital_params)

    respond_to do |format|
      if @hospital.save
        format.html { redirect_to @hospital, notice: 'Hospital was successfully created.' }
        format.json { render :show, status: :created, location: @hospital }
      else
        format.html { render :new }
        format.json { render json: @hospital.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hospitals/1
  # PATCH/PUT /hospitals/1.json
  def update
    respond_to do |format|
      if @hospital.update(hospital_params)
        format.html { redirect_to @hospital, notice: 'Hospital was successfully updated.' }
        format.json { render :show, status: :ok, location: @hospital }
      else
        format.html { render :edit }
        format.json { render json: @hospital.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hospitals/1
  # DELETE /hospitals/1.json
  def destroy
    @hospital.destroy
    respond_to do |format|
      format.html { redirect_to hospitals_url, notice: 'Hospital was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hospital
      @hospital = Hospital.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hospital_params
      params.fetch(:hospital, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hospitals_helper.rb
module HospitalsHelper
end

app/views/hospitals/_form.html.erb
<%= form_with(model: hospital, local: true) do |form| %>
  <% if hospital.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(hospital.errors.count, "error") %> prohibited this hospital from being saved:</h2>

      <ul>
      <% hospital.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/hospitals/busca_hospitais.html.erb
<div class="container">
    <div class="container" style="text-align: center;">
        <img src="img/logo.png" class="img-responsive" id="logo"/>  
        <a class="search" href="/map">
            <button class="btn btn-primary btn-block" id="search">Buscar</button>
        </a>
    </div>
</div>
<style>
    body {
        background-color: #333;
    }
    #search {
        font-size: 25px;
        padding: 24px;
    }
    #logo {
        max-height: 70vh;
    }
    .search a:hover, #search:hover {
      text-decoration: none;
    }
</style>

app/views/hospitals/edit.html.erb
<h1>Editing Hospital</h1>

<%= render 'form', hospital: @hospital %>

<%= link_to 'Show', @hospital %> |
<%= link_to 'Back', hospitals_path %>

app/views/hospitals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Hospitals</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hospitals.each do |hospital| %>
      <tr>
        <td><%= link_to 'Show', hospital %></td>
        <td><%= link_to 'Edit', edit_hospital_path(hospital) %></td>
        <td><%= link_to 'Destroy', hospital, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hospital', new_hospital_path %>

app/views/hospitals/new.html.erb
<h1>New Hospital</h1>

<%= render 'form', hospital: @hospital %>

<%= link_to 'Back', hospitals_path %>

app/views/hospitals/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_hospital_path(@hospital) %> |
<%= link_to 'Back', hospitals_path %>

app/views/hospitals/showmap.html.erb
<!DOCTYPE html>
<html>
  <head>
    <style>
    a {
      color: #FFF;
    }
    a:hover, a:visited, a:focus {
      color: #FFF;]
      text-decoration: none;
      background: transparent;
    }
    #map {
      height: 100vh;
      width: 100%;
    }
    #logo {
      position: absolute;
      top: 0;
      width: 100%;
      text-align: center;
      background-color: white;
    }
    .bottom {
      width: 100%;
      position: absolute;
      bottom: 30px;
      padding: 30px 90px;
    }
    .bottom a:hover, #back:hover {
      text-decoration: none;
    }
    #back {
      padding: 24px;
      font-size: 25px;
    }
    #medicalhelp {
       height: 18vh;
    }
    </style>
  </head>
  <body>
    <div id="map" class="relative">
    </div>

    <script>
      function initMap() {
        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 15,
          center: {lat: -8.05428, lng: -34.8813},
        });

        var icons = {
          consult_u: {
            icon: {
            size: new google.maps.Size(20, 20),
            scaledSize: new google.maps.Size(20, 20),
            url:"img/pin_consultorios.png"
            }
          },
          clinica_u: {
            icon: {
            size: new google.maps.Size(20, 20),
            scaledSize: new google.maps.Size(20, 20),
            url:"img/pin_centroespecializado.png"
            }
          },
          centro_u: {
            icon: {
            size: new google.maps.Size(20, 20),
            scaledSize: new google.maps.Size(20, 20),
            url:"img/pin_centrodesaude.png"
            }
          },
          geral_u: {
            icon: {
            size: new google.maps.Size(20, 20),
            scaledSize: new google.maps.Size(20, 20),
            url:"img/pin_hospitalgeral.png"
            }
          },
          spec_u: {
            icon: {
            size: new google.maps.Size(20, 20),
            scaledSize: new google.maps.Size(20, 20),
            url:"img/pin_hospitalespecializado.png"
            }
          }
        };

        //var infoWindow = new google.maps.InfoWindow({map: map});
        // Try HTML5 geolocation.
        if (navigator.geolocation) {
          navigator.geolocation.getCurrentPosition(function(position) {
            var pos = {
              lat: position.coords.latitude,
              lng: position.coords.longitude
            };
            map.setCenter(pos);
          }, function() {
            handleLocationError(true, infoWindow, map.getCenter());
          });
        } else {
          // Browser doesn't support Geolocation
          handleLocationError(false, infoWindow, map.getCenter());
        }

        "<% @consultorios.each do |consultorio| %>"
          var coordenadas = new google.maps.LatLng("<%= consultorio.nu_latitude %>" ,"<%= consultorio.nu_longitude %>");
          var marker = new google.maps.Marker({
            position: coordenadas,
            //map: map
            icon: icons.consult_u.icon,
            title: "<%= consultorio.no_fantasia %>"
          });
          marker.setMap(map);
        "<% end %>"

        "<% @clinicas.each do |clinica| %>"
          var coordenadas = new google.maps.LatLng("<%= clinica.nu_latitude %>" ,"<%= clinica.nu_longitude %>");
          var marker = new google.maps.Marker({
            position: coordenadas,
            //map: map
            icon: icons.clinica_u.icon,
            title: "<%= clinica.no_fantasia %>"
          });
          marker.setMap(map);
        "<% end %>"

        "<% @centrossaude.each do |centro| %>"
          var coordenadas = new google.maps.LatLng("<%= centro.nu_latitude %>" ,"<%= centro.nu_longitude %>");
          var marker = new google.maps.Marker({
            position: coordenadas,
            //map: map
            icon: icons.centro_u.icon,
            title: "<%= centro.no_fantasia %>"
          });
          marker.setMap(map);
        "<% end %>"

        "<% @hospgerais.each do |hospg| %>"
          var coordenadas = new google.maps.LatLng("<%= hospg.nu_latitude %>" ,"<%= hospg.nu_longitude %>");
          var marker = new google.maps.Marker({
            position: coordenadas,
            //map: map
            icon: icons.geral_u.icon,
            title: "<%= hospg.no_fantasia %>"
          });
          marker.setMap(map);
        "<% end %>"

        "<% @hospespecializados.each do |hospe| %>"
          var coordenadas = new google.maps.LatLng("<%= hospe.nu_latitude %>" ,"<%= hospe.nu_longitude %>");
          var marker = new google.maps.Marker({
            position: coordenadas,
            //map: map
            icon: icons.spec_u.icon,
            title: "<%= hospe.no_fantasia %>"
          });
          marker.setMap(map);
        "<% end %>"

        marker.addListener('click', function() {
          map.setZoom(10);
          map.setCenter(marker.getPosition());
        });

      }
      function handleLocationError(browserHasGeolocation, infoWindow, pos) {
        infoWindow.setPosition(pos);
        infoWindow.setContent(browserHasGeolocation ?
                              'Error: Falha na geolocalização, verifique permissão do browser' :
                              'Error: Your browser doesn\'t support geolocation.');
      }
    </script>
    <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA3tOwxd4AhG7MSIB-suRz0ZqjiLlq3pTs&callback=initMap">
    </script>
    <div id="logo">
      <img src="img/logo.png" id="medicalhelp"/>
    </div>
    <div class="bottom">
      <a href="../">
        <button id="back" class="btn btn-block btn-primary">Voltar</button>
      </a>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MHR</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>